<?php

require_once 'Gazel/Form.php';

/**
 * Generated By Gazel Studio
 *
 *
 *
 * @Modification 07-03-2012
 */
class LightArticle_Form_Admin extends Gazel_Form
{

    public function prepareForm($val)
    {
        $elements = array(); 
        										$translate= Zend_Registry::get('translate');
        									 
        											$elements[] = array(
        											'type'		=> 'text',
        											'name'		=> 'article_title',
        											'label'		=> $translate->_('Title'),
        											'value'		=> $val['article_title'],
        													'size'		=> 45,
        												'required'	=> 1
        										); 
        										 
        											$elements[] = array(
        											'type'		=> 'textarea',
        											'name'		=> 'article_shortdesc',
        											'label'		=> $translate->_('Short Desc'),
        											'value'		=> $val['article_shortdesc'],
        												'required'	=> 1
        										); 
        										 
        											$elements[] = array(
        											'type'		=> 'text',
        											'name'		=> 'article_writer',
        											'label'		=> $translate->_('Writer'),
        											'value'		=> $val['article_writer'],
        													'size'		=> 45,
        												'required'	=> 0
        										); 
        										 
        											$elements[] = array(
        											'type'		=> 'richeditor',
        											'name'		=> 'article_content',
        											'label'		=> $translate->_('Content'),
        											'value'		=> $val['article_content'],
        												'required'	=> 0
        										); 
        										 
        											
        										$this->addNewElements($elements);
    }


}

